/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastro;

import java.awt.event.WindowAdapter;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ead
 */
public class AtualizarJF extends javax.swing.JFrame {
    private ListarJF listarjf;
    private JTable tabela;
    /**
     * Creates new form AtualizarJF
     */

    public AtualizarJF(JTable tabela) {
        this.tabela = tabela;
        initComponents();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomeAt = new javax.swing.JTextField();
        txtEnderecoAt = new javax.swing.JTextField();
        txtCpfAt = new javax.swing.JTextField();
        txtMatriculaAt = new javax.swing.JTextField();
        txtCursoAt = new javax.swing.JTextField();
        cbSexoAt = new javax.swing.JComboBox<>();
        SalvarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 3, 24)); // NOI18N
        jLabel1.setText("Atualizar");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel2.setText("Nome : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel3.setText("Endereco :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel4.setText("Cpf :");

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel5.setText("Matricula :");

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel6.setText("Curso :");

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel7.setText("Sexo :");

        cbSexoAt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o item", "Masculino", "Feminino", "Prefiro nao dizer" }));

        SalvarB.setText("Salvar");
        SalvarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCursoAt)
                                    .addComponent(txtNomeAt)
                                    .addComponent(txtEnderecoAt)
                                    .addComponent(txtCpfAt)
                                    .addComponent(txtMatriculaAt)
                                    .addComponent(cbSexoAt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(SalvarB, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEnderecoAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCpfAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMatriculaAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCursoAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cbSexoAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(SalvarB)
                .addGap(0, 137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBActionPerformed
        AlunoDAO alundao = new AlunoDAO();
        int ls =  tabela.getSelectedRow();
        int id = (int) tabela.getValueAt(ls, 0); 

         try{
             String nome = txtNomeAt.getText().trim();
             String endereco = txtEnderecoAt.getText().trim();
             String cpf = txtCpfAt.getText().trim();
             String curso = txtCursoAt.getText().trim();
             String matricula= txtMatriculaAt.getText().trim();
             int sexo = cbSexoAt.getSelectedIndex();
             String sexotxt = cbSexoAt.getSelectedItem().toString();
             System.out.println("passou");
             if(nome.isEmpty()||endereco.isEmpty()||cpf.isEmpty()||curso.isEmpty()||matricula.isEmpty()||sexo == 0){
                 JOptionPane.showMessageDialog(this, 
                         "É necessario preencher todos os campos ou selecionar",
                         "Campos nao preenchidos",
                         JOptionPane.WARNING_MESSAGE);
             }else{
                 Aluno alunoatualizado = new Aluno(curso, matricula, id, nome, endereco, sexotxt, cpf);
                 alundao.atualizarUsuario(alunoatualizado);
                 this.dispose();
             }  
        }catch(SQLException e ){
                 JOptionPane.showMessageDialog(this, 
                         "Erro: "+e.getMessage(),
                         "Erro",
                         JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_SalvarBActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AtualizarJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AtualizarJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AtualizarJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AtualizarJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AtualizarJF().setVisible(true);
//            }
//        });
//    }

    public JComboBox<String> getCbSexoAt() {
        return cbSexoAt;
    }

    public void setCbSexoAt(JComboBox<String> cbSexoAt) {
        this.cbSexoAt = cbSexoAt;
    }

    public JTextField getTxtCpfAt() {
        return txtCpfAt;
    }

    public void setTxtCpfAt(JTextField txtCpfAt) {
        this.txtCpfAt = txtCpfAt;
    }

    public JTextField getTxtCursoAt() {
        return txtCursoAt;
    }

    public void setTxtCursoAt(JTextField txtCursoAt) {
        this.txtCursoAt = txtCursoAt;
    }

    public JTextField getTxtEnderecoAt() {
        return txtEnderecoAt;
    }

    public void setTxtEnderecoAt(JTextField txtEnderecoAt) {
        this.txtEnderecoAt = txtEnderecoAt;
    }

    public JTextField getTxtMatriculaAt() {
        return txtMatriculaAt;
    }

    public void setTxtMatriculaAt(JTextField txtMatriculaAt) {
        this.txtMatriculaAt = txtMatriculaAt;
    }

    public JTextField getTxtNomeAt() {
        return txtNomeAt;
    }

    public void setTxtNomeAt(JTextField txtNomeAt) {
        this.txtNomeAt = txtNomeAt;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalvarB;
    private javax.swing.JComboBox<String> cbSexoAt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCpfAt;
    private javax.swing.JTextField txtCursoAt;
    private javax.swing.JTextField txtEnderecoAt;
    private javax.swing.JTextField txtMatriculaAt;
    private javax.swing.JTextField txtNomeAt;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtCpf() {
        return txtCpfAt;
    }

    public void setTxtCpf(JTextField txtCpf) {
        this.txtCpfAt = txtCpf;
    }

    public JTextField getTxtCurso() {
        return txtCursoAt;
    }

    public void setTxtCurso(JTextField txtCurso) {
        this.txtCursoAt = txtCurso;
    }

    public JTextField getTxtEndereço() {
        return txtEnderecoAt;
    }

    public void setTxtEndereço(JTextField txtEndereço) {
        this.txtEnderecoAt = txtEndereço;
    }

    public JTextField getTxtMatricula() {
        return txtMatriculaAt;
    }

    public void setTxtMatricula(JTextField txtMatricula) {
        this.txtMatriculaAt = txtMatricula;
    }

    public JTextField getTxtNome() {
        return txtNomeAt;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNomeAt = txtNome;
    }
    
}

